apiVersion: v1
kind: Pod
metadata:
  name: ben-mongodb-test
spec:
  containers:
  - name: mongodb
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: password
    volumeMounts:
    - name: init-script
      mountPath: /docker-entrypoint-initdb.d/mongo-init.js
    ports:
    - containerPort: 27017
  - name: ben-mongodb
    image: ben-mongodb:v1
    env:
    - name: BEN_DB_READ_OPS
      value: '0'
    - name: BEN_DB_WRITE_OPS
      value: '10'
  volumes:
  - name: init-script
    configMap:
      name: mongo-initjs

